/**
 * Indicate a screen where a component exists
 */
const COMPONENTS_PAGE = {}

COMPONENTS_PAGE.HOME = 'HOME'
COMPONENTS_PAGE.BROWSE = 'BROWSE'
COMPONENTS_PAGE.PRODUCT_DETAILS = 'PRODUCT_DETAILS'
COMPONENTS_PAGE.DEEL_DAILY = 'DEEL_DAILY'
COMPONENTS_PAGE.FAVOURITES = 'FAVOURITES'
COMPONENTS_PAGE.PRODUCTS_LIST = 'PRODUCTS_LIST'
COMPONENTS_PAGE.SHOPS = 'SHOPS'
COMPONENTS_PAGE.SHOP = 'SHOP'
COMPONENTS_PAGE.MY_SHOP = 'MY_SHOP'
COMPONENTS_PAGE.POST_PRODUCT = 'POST_PRODUCT'

Object.freeze(COMPONENTS_PAGE);
export default COMPONENTS_PAGE
