const CouponTypeConst = {};

CouponTypeConst.FIXED_AMOUNT = 'FIXED_AMOUNT';
CouponTypeConst.FREE_DELIVERY = 'FREE_DELIVERY';
CouponTypeConst.PERCENTAGE_DISCOUNT = 'PERCENTAGE_DISCOUNT';
CouponTypeConst.PERCENTAGE_DISCOUNT_WITH_FREE_DELIVERY = 'PERCENTAGE_DISCOUNT_WITH_FREE_DELIVERY';
CouponTypeConst.FIXED_AMOUNT_WITH_FREE_DELIVERY = 'FIXED_AMOUNT_WITH_FREE_DELIVERY';

Object.freeze(CouponTypeConst);
export default CouponTypeConst;
